#pragma once

#define EE_HANDS

#define SPLIT_USB_DETECT
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_PIN_SWAP
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1


#define MATRIX_ROW_PINS { GP3, GP4, GP5, GP6, GP9 } // GP3-9 are rows, likely need 3-6, 9
#define MATRIX_COL_PINS { GP25, GP24, GP23, GP22, GP21, GP20  }

#define TAPPING_TERM 210
#define PERMISSIVE_HOLD
#define CHORDAL_HOLD

#define RGB_TYPING_IDLE_TIMEOUT 10000

#define RGB_TYPING_EFFECT RGB_MATRIX_TYPING_HEATMAP

#define WS2812_DI_PIN GP2
#define WS2812_RGBW true


#define RGBLED_SPLIT { 124, 124 }

#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_RIVERFLOW
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL

#define RGB_MATRIX_SPLIT { 124, 124 }
#define RGB_MATRIX_DEFAULT_ON true
#define RGB_MATRIX_HUE_STEP 1

#define LEFT_UNDERGLOW_START 30
#define LEFT_UNDERGLOW_END 94
#define LEFT_TRACKBALL_START 95
#define LEFT_TRACKBALL_END 123

#define RIGHT_UNDERGLOW_START 154
#define RIGHT_UNDERGLOW_END 218
#define RIGHT_TRACKBALL_START 219
#define RIGHT_TRACKBALL_END 247
// left 30 keys, 65 underglow, 29 trackball
// right same as above
#define RGB_MATRIX_LED_COUNT 248
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_RIVERFLOW
#define RGB_MATRIX_DEFAULT_VAL 255
#define RGB_MATRIX_DEFAULT_HUE 140
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255
#define RGB_MATRIX_DRIVER custom

#define SPI_DRIVER SPID1
#define SPI_SCK_PIN GP14
#define SPI_MISO_PIN GP12
#define SPI_MOSI_PIN GP15
#define POINTING_DEVICE_CS_PIN GP13
#define PMW3389_CS_PIN GP13

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_COMBINED

//#define ROTATIONAL_TRANSFORM_ANGLE 90
#define PMW33XX_CPI 1000
#define POINTING_DEVICE_ROTATION_270  // rotates left
#define POINTING_DEVICE_ROTATION_270_RIGHT
#define POINTING_DEVICE_INVERT_X // inverts trackball x left
#define POINTING_DEVICE_INVERT_X_RIGHT // inverts trackball x

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17

#define DEBUG_ENABLE
//#define POINTING_DEVICE_DEBUG

#define HSV_DEFAULT_BLUE 140, 255, 255
