#pragma once

//#define EE_HANDS

//#define SPLIT_USB_DETECT
//#define SERIAL_USART_FULL_DUPLEX
//#define SERIAL_USART_PIN_SWAP
//#define SERIAL_USART_TX_PIN GP0
//#define SERIAL_USART_RX_PIN GP1

//#define MATRIX_ROWS 6
//#define MATRIX_COLS 8
#define MATRIX_ROW_PINS { GP29 }
#define MATRIX_COL_PINS { GP2 }


#define SPI_DRIVER SPID1
#define SPI_SCK_PIN GP14
#define SPI_MISO_PIN GP12
#define SPI_MOSI_PIN GP15
#define POINTING_DEVICE_CS_PIN GP13
#define PMW3389_CS_PIN GP13

//#define PMW33XX_LIFTOFF_DISTANCE 0x06
#define PMW33XX_CPI 1000
#define ROTATIONAL_TRANSFORM_ANGLE 90
#define POINTING_DEVICE_INVERT_X // inverts trackball x

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17

#define DEBUG_ENABLE
#define DEBUG_MOUSE_ENABLE
#define POINTING_DEVICE_DEBUG
