#pragma once

#define EE_HANDS

#define SPLIT_USB_DETECT
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_PIN_SWAP
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1


#define MATRIX_ROW_PINS { GP3, GP4, GP5, GP6, GP9 } // GP3-9 are rows, likely need 3-6, 9
#define MATRIX_COL_PINS { GP25, GP24, GP23, GP22, GP21, GP20  }

#define WS2812_DI_PIN GP2


#define RGBLED_SPLIT { 30, 30 }
#define RGBLIGHT_SPLIT { 30, 30 }
#define RGBLIGHT_LED_COUNT 60
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_SNAKE

#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP

#define RGB_MATRIX_SPLIT { 30, 30 }
#define RGB_MATRIX_DEFAULT_ON true
#define RGB_MATRIX_LED_COUNT 60
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TYPING_HEATMAP
#define RGB_MATRIX_DEFAULT_VAL 255
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255

#define SPI_DRIVER SPID1
#define SPI_SCK_PIN GP14
#define SPI_MISO_PIN GP12
#define SPI_MOSI_PIN GP15
#define POINTING_DEVICE_CS_PIN GP13
#define PMW3389_CS_PIN GP13

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_COMBINED

//#define ROTATIONAL_TRANSFORM_ANGLE 90
#define PMW33XX_CPI 1000
#define POINTING_DEVICE_ROTATION_270  // rotates left
#define POINTING_DEVICE_ROTATION_270_RIGHT
#define POINTING_DEVICE_INVERT_X // inverts trackball x left
#define POINTING_DEVICE_INVERT_X_RIGHT // inverts trackball x

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17

#define DEBUG_ENABLE
#define DEBUG_MOUSE
