# Build Options
#   change yes to no to disable

AUDIO_SUPPORTED = no
# RGB Matrix disabled for testing
RGB_MATRIX_SUPPORTED = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812

# RGBLIGHT enabled for testing
RGBLIGHT_SUPPORTED = yes
RGBLIGHT_ENABLE = no
RGBLIGHT_DRIVER = ws2812

BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor
MOUSEKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes

# Trackball
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3389


CONSOLE_ENABLE=yes
